name: Verify Clarity Contracts in Monorepo
on:
  pull_request:
    branches: [main]
    paths:
      - "packages/*/contracts/**/*.clar"

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to get full history for detecting changes

      # Find all packages with Clarity contracts
      - name: Find packages with Clarity contracts
        id: find-packages
        run: |
          PACKAGES=$(find packages -type d -name "contracts" -path "*/packages/*/contracts" | cut -d'/' -f2 | sort | uniq | tr '\n' ' ')
          echo "Found packages with Clarity contracts: $PACKAGES"
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT

      # Run verification for each package
      - name: Verify Clarity Contracts
        id: verify
        uses: proj-clarity-esbmc/clara_github_action@v0.1.0-alpha
        with:
          # Dynamically set contracts directory based on found packages
          contracts_dir: ${{ join(fromJSON('["packages/' + join(steps.find-packages.outputs.packages, '/contracts","packages/') + '/contracts"]'), ',') }}
          fail_on_issue: "true"
          container_version: "latest"
          ast_container_repo: "saad963/esbmc-container"
          esbmc_container_repo: "saad963/esbmc-container"

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        if: always() # Run even if verification fails
        with:
          sarif_file: ${{ steps.verify.outputs.sarif_report }}

      # Create summary report
      - name: Create verification summary
        if: always()
        run: |
          echo "# Clarity Contracts Verification Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ "${{ steps.verify.outputs.verification_status }}" == "success" ]; then
            echo "✅ **All contracts verified successfully**" >> $GITHUB_STEP_SUMMARY
          elif [ "${{ steps.verify.outputs.verification_status }}" == "no_changes" ]; then
            echo "ℹ️ **No modified Clarity functions detected**" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ **Verification issues detected**" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "See SARIF report for details." >> $GITHUB_STEP_SUMMARY
          fi
