name: Test Clarity Verification Locally
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Required to get full history for detecting changes

      - name: Verify Clarity Contracts
        id: verify
        uses: ./ # Use the local action
        with:
          contracts_dir: "./test-contracts"
          fail_on_issue: "false" # Don't fail the workflow for testing
          github_token: ${{ github.token }}

      - name: Display verification results
        run: |
          echo "Verification status: ${{ steps.verify.outputs.verification_status }}"
          echo "SARIF report: ${{ steps.verify.outputs.sarif_report }}"
          cat ${{ steps.verify.outputs.sarif_report }}
